<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2</name>
   <tag></tag>
   <elementGuidId>7da24975-1a65-449c-8e23-a6fbf7c6f5d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body.md-dialog-is-showing:nth-child(4) div.md-dialog-container:nth-child(10) md-dialog._md.md-transition-in:nth-child(2) div.dialog-alert-box.layout-column div.dialog-footer.button_message > button.button.radius.md-raised.md-button.md-ink-ripple:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body[@class='md-dialog-is-showing']/div[7]/md-dialog[@role='dialog']//button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button radius md-raised md-button md-ink-ripple</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>ctrl.accept()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>نعم
        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogContent_380&quot;)/div[@class=&quot;dialog-alert-box layout-column&quot;]/div[@class=&quot;dialog-footer button_message&quot;]/button[@class=&quot;button radius md-raised md-button md-ink-ripple&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-dialog[@id='dialogContent_380']/div/div[2]/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ملف مرفق 1? هل أنت متأكد أنك تريد حذف'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سحب وإفلات'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لا'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-dialog/div/div[2]/button</value>
   </webElementXpaths>
</WebElementEntity>
