<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>740cf3f0-de87-4e85-90fc-98db576b3b3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sub-view-wrapper']/ui-view/div/div[2]/div[2]/div/div/accordion-directive/accordion-item[4]/accordion-content/div/manage-attachment-directive/div/div/md-menu-bar/md-menu/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>المرفقات</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-view-wrapper&quot;)/ui-view[@class=&quot;sub-view layout-column flex&quot;]/div[@class=&quot;page-content flex&quot;]/div[@class=&quot;content layout-column&quot;]/div[@class=&quot;layout-column flex&quot;]/div[@class=&quot;scrollable-element ps ps--theme_default ps--active-y&quot;]/div[@class=&quot;page-padding&quot;]/accordion-directive[@class=&quot;validation&quot;]/accordion-item[4]/accordion-content[1]/div[@class=&quot;layout-row&quot;]/manage-attachment-directive[@class=&quot;flex&quot;]/div[@class=&quot;layout-column&quot;]/div[@class=&quot;layout-row&quot;]/md-menu-bar[@class=&quot;p0 _md md-keyboard-mode&quot;]/md-menu[@class=&quot;md-menu _md&quot;]/button[@class=&quot;md-raised md-button md-ink-ripple&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-view-wrapper']/ui-view/div/div[2]/div[2]/div/div/accordion-directive/accordion-item[4]/accordion-content/div/manage-attachment-directive/div/div/md-menu-bar/md-menu/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إدارة مرفقات الكتاب'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='قالب توضيف - Template Employment Ad'])[1]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحميل مرفق'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سحب وإفلات'])[1]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='المرفقات']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
   </webElementXpaths>
</WebElementEntity>
