<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ _iframe-main-document</name>
   <tag></tag>
   <elementGuidId>3bda6635-c557-4272-8601-986a0d2a238b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html//iframe[@id='iframe-main-document']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>ctrl.mainDocument &amp;&amp; ctrl.editMode</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe-main-document</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe-main-document flex</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>http://eblaepm.no-ip.org/we/wordeditorframe.aspx?&amp;ui=ar&amp;access_token_ttl=0&amp;WOPISrc=http%3A%2F%2Feblaepm.no-ip.org%3A9080%2FCMSServices%2Fservice%2Fcms-entity%2Fwopi%2Ffiles%2FAAEpY29tLmVibGEuY21zLm1vZGVsLnZpZXdlci5PZmZpY2VWaWV3ZXJVcmzw__wOYm9va3Mvb3V0Z29pbmf8BGRvY3j8JGEzZTQ4NjJkLTk5YTItNDMyOS1iMjczLTkyNzU0YWI2ODk1OP_8JDFkZDFlYmEzLTZkODgtNDc4NC1iZDUwLTI1ZDJhNzhlOTEwMgA&amp;rand=7afad87af2c043aba180450f1341b371</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://eblaepm.no-ip.org/we/wordeditorframe.aspx?&amp;ui=ar&amp;access_token_ttl=0&amp;WOPISrc=http%3A%2F%2Feblaepm.no-ip.org%3A9080%2FCMSServices%2Fservice%2Fcms-entity%2Fwopi%2Ffiles%2FAAEpY29tLmVibGEuY21zLm1vZGVsLnZpZXdlci5PZmZpY2VWaWV3ZXJVcmzw__wOYm9va3Mvb3V0Z29pbmf8BGRvY3j8JGEzZTQ4NjJkLTk5YTItNDMyOS1iMjczLTkyNzU0YWI2ODk1OP_8JDFkZDFlYmEzLTZkODgtNDc4NC1iZDUwLTI1ZDJhNzhlOTEwMgA&amp;rand=7afad87af2c043aba180450f1341b371</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe-main-document&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe-main-document']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframe-parent']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
