<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-icon_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>f6af1de1-2aa8-4ba7-bc91-9119f852e51f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sub-view-wrapper']/ui-view/div/div[2]/div[2]/div/div/div[2]/div/accordion-directive/accordion-item/accordion-content/div/div[2]/button/md-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-svg-icon</name>
      <type>Main</type>
      <value>note-multiple-outline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>note-multiple-outline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-view-wrapper&quot;)/ui-view[@class=&quot;sub-view layout-column flex&quot;]/div[@class=&quot;page-content flex&quot;]/div[@class=&quot;content layout-column&quot;]/div[@class=&quot;layout-column flex&quot;]/div[@class=&quot;scrollable-element ps ps--theme_default ps--active-y&quot;]/div[@class=&quot;simple-padding layout-row flex&quot;]/div[@class=&quot;simple-viewer layout-row flex-70&quot;]/div[@class=&quot;layout-column flex&quot;]/accordion-directive[@class=&quot;layout-column flex&quot;]/accordion-item[@class=&quot;layout-column active pass-validation&quot;]/accordion-content[@class=&quot;layout-column&quot;]/div[@class=&quot;layout-row&quot;]/div[@class=&quot;icon-relative ng-enter-prepare&quot;]/button[@class=&quot;md-raised md-icon-button md-button md-ink-ripple&quot;]/md-icon[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-view-wrapper']/ui-view/div/div[2]/div[2]/div/div/div[2]/div/accordion-directive/accordion-item/accordion-content/div/div[2]/button/md-icon</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test1811-1'])[1]/following::md-icon[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رفع محتوى'])[1]/following::md-icon[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إدارة تكنولوجيا المعلومات selected'])[1]/preceding::md-icon[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//accordion-content/div/div[2]/button/md-icon</value>
   </webElementXpaths>
</WebElementEntity>
