<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ _md-bar</name>
   <tag></tag>
   <elementGuidId>f42467f7-052b-48bc-82ee-9d59a593df8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sub-view-wrapper']/ui-view/div/div[2]/div[2]/div/div/div[2]/div/accordion-directive/accordion-item/accordion-title/div/span/div/div/md-switch/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-bar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-view-wrapper&quot;)/ui-view[@class=&quot;sub-view layout-column flex&quot;]/div[@class=&quot;page-content flex&quot;]/div[@class=&quot;content layout-column&quot;]/div[@class=&quot;layout-column flex&quot;]/div[@class=&quot;scrollable-element ps ps--theme_default ps--active-y&quot;]/div[@class=&quot;simple-padding layout-row flex&quot;]/div[@class=&quot;simple-viewer layout-row flex-70&quot;]/div[@class=&quot;layout-column flex&quot;]/accordion-directive[@class=&quot;layout-column flex&quot;]/accordion-item[@class=&quot;layout-column active&quot;]/accordion-title[1]/div[@class=&quot;outline-none cursor-pointer accordion-title layout-align-start-center layout-row&quot;]/span[@class=&quot;flex&quot;]/div[@class=&quot;layout-align-start-center layout-row&quot;]/div[@class=&quot;layout-align-center-center layout-row&quot;]/md-switch[@class=&quot;m0 top-switch-handler ng-valid ng-dirty ng-valid-parse ng-touched ng-empty&quot;]/div[@class=&quot;md-container&quot;]/div[@class=&quot;md-bar&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sub-view-wrapper']/ui-view/div/div[2]/div[2]/div/div/div[2]/div/accordion-directive/accordion-item/accordion-title/div/span/div/div/md-switch/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صادر ورقي'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صادر الكترونى'])[1]/preceding::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-switch/div/div</value>
   </webElementXpaths>
</WebElementEntity>
