<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-icon_1_2_3</name>
   <tag></tag>
   <elementGuidId>c7752670-6ef8-4b76-98e9-8585afaf24e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//md-tab-content[@id='tab-content-3853']/div/md-content/div/div[2]/md-card/md-table-container/div/table/tbody/tr/td[4]/div/md-menu-bar/md-menu/button/md-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-svg-icon</name>
      <type>Main</type>
      <value>plus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>plus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-content-3853&quot;)/div[1]/md-content[@class=&quot;md-padding white-bg _md&quot;]/div[@class=&quot;scrollable-element ps ps--theme_default layout-column&quot;]/div[@class=&quot;layout-column flex&quot;]/md-card[@class=&quot;card-overlay _md layout-column md-whiteframe-3dp&quot;]/md-table-container[1]/div[@class=&quot;scrollable-element ps ps--theme_default flex&quot;]/table[@class=&quot;ng-pristine ng-untouched ng-valid md-table ng-not-empty md-row-select&quot;]/tbody[@class=&quot;md-body&quot;]/tr[@class=&quot;md-row&quot;]/td[@class=&quot;md-cell&quot;]/div[@class=&quot;layout-align-start-center layout-row flex&quot;]/md-menu-bar[@class=&quot;_md md-keyboard-mode&quot;]/md-menu[@class=&quot;md-menu _md&quot;]/button[@class=&quot;md-icon-button&quot;]/md-icon[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-tab-content[@id='tab-content-3853']/div/md-content/div/div[2]/md-card/md-table-container/div/table/tbody/tr/td[4]/div/md-menu-bar/md-menu/button/md-icon</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تم الرد'])[1]/following::md-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='لا يحتاج للرد'])[2]/following::md-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أصلى'])[1]/preceding::md-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نسخة'])[1]/preceding::md-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-menu/button/md-icon</value>
   </webElementXpaths>
</WebElementEntity>
